[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_lending_borrowing_platform = "EvHuYVEgrSZWhqsLvqXL2KwWeHXRcSgVWbYMm4MdgB1G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/bprime/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
